### PR TITLE
Restructuring and renaming of components

### PR DESCRIPTION
**Pull request by awinny**
**Describe pull-request**
- Renamed and moved files
- Removed non recommended examples

### CODE REVIEW

**Comment by awinny** [comment]
Connected to #173

**Review by helloimela — DISMISSED** [review]
👍

**Comment by helloimela** [comment]
Please remove public/index.html

**Review by helloimela — DISMISSED** [review]
Looks good 👍

**Review by helloimela — APPROVED** [review]

**Pull request merged**
