### PR TITLE
Move external dependencies to the theme

### LINKED ISSUE #130: Bug - IE style for bootstrap element inside Corporate-ui component is overwritten
**Describe the bug**<br/>
in IE, if we have bootstrap element inside CUI component, for example dropdown inside header, the styling for bootstrap will be overwritten by the component style

**To Reproduce**<br/>
1. In IE, go to c-navigation example in Storybook
2. See the dropdown example

**Expected behavior**<br/>
A better solution for the styling of bootstrap element inside CUI component

**Desktop (please complete the following information):**<br/>
 - OS: Windows
 - Browser IE
 - Version 11

**Additional context**<br/>
Related issue #126

### PR DESCRIPTION
**Pull request by awinny**
**Describe pull-request**</br>
- Moved theme related things out from ccorporate-ui to scania-theme
- Changed components to use new theme setup
- Added store part for themes
- Removed theme generation task
- Changed handling of items in components to be mutable from inside the component
- Refactored the unittests structure
- Re added corporate-ui version to html node setter

**Solving issue**</br>
Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)
Fixes: #130 #129 #81 

**Additional context**<br/>
This feature is pretty big and contains a loot of new things so it needs to be tested in detail.

### CODE REVIEW

**Comment by helloimela** [comment]
- Favicon not working in IE
- default navigation on mobile mode should be close
- suggestion : change 
`import { theme } from 'scania-theme';
addTheme(theme);`
into
`import { scania } from 'scania-theme';
addTheme(scania);`

**Comment by awinny** [comment]
- Favicon in IE is not working atm (we have decided to look for a fix on this later)
- mobile navigation default mode has been changed back to previous state
- import module name has been decided to not be changed but instead used with "as" syntax

**Review by helloimela — APPROVED** [review]
Tested in different environments: CDN, React, Angular.
Notes: in CDN, need to load scania-theme before corporate-ui script.

**Comment by helloimela** [comment]
Todo: need to update themes documentation

**Comment by awinny** [comment]
So to keep it simple, always put theme script before corporate-ui script tag as in the examples for now.
We also need to do some work on the initial style for corporate (when no theme has been selected).

**Pull request merged**
